[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
obscura = "OBSCurAXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.localnet]
obscura = "OBSCurAXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[scripts]
test = "yarn run ts-mocha -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
